import type { CardType } from './MatchSnapshot';

/**
 * Public event contract broadcast over SSE.
 *
 * These payloads are intentionally decoupled from the upstream provider: the
 * change detector translates provider data into exactly these shapes.
 */

export type MatchEventType = 'goal' | 'card' | 'substitution';

export type EventSeverity = 'CRITICAL' | 'HIGH' | 'MEDIUM' | 'LOW';

export type CommentaryStyle = 'standard' | 'concise' | 'professional';

export interface GoalEventPayload {
  matchId: string;
  team: string;
  player: string;
  minute: number;
  /** Score after the goal, e.g. "2-1" (home-away). */
  score: string;
}

export interface CardEventPayload {
  matchId: string;
  team: string;
  player: string;
  minute: number;
  cardType: CardType;
}

export interface SubstitutionEventPayload {
  matchId: string;
  team: string;
  playerIn: string;
  playerOut: string;
  minute: number;
}

export type MatchEventPayload = GoalEventPayload | CardEventPayload | SubstitutionEventPayload;

export interface BaseMatchEvent {
  /** Stable, de-duplicated identifier; also emitted as the SSE `id:` field. */
  readonly id: string;
  readonly matchId: string;
  /** Epoch millis at which the service detected the event. */
  readonly detectedAt: number;
  /** Human-readable narrative generated by the CommentaryEngine. */
  commentary?: string;
  /** Extensible event importance level. */
  severity?: EventSeverity;
}

export interface GoalEvent extends BaseMatchEvent {
  readonly type: 'goal';
  readonly payload: GoalEventPayload;
}

export interface CardEvent extends BaseMatchEvent {
  readonly type: 'card';
  readonly payload: CardEventPayload;
}

export interface SubstitutionEvent extends BaseMatchEvent {
  readonly type: 'substitution';
  readonly payload: SubstitutionEventPayload;
}

/** Discriminated union of everything the service can broadcast. */
export type MatchEvent = GoalEvent | CardEvent | SubstitutionEvent;

export interface SseFormatOptions {
  format?: 'commentary' | 'legacy';
  style?: CommentaryStyle;
}

/**
 * Serialize an event into a wire-format SSE message.
 *
 * In legacy format (default for backwards compatibility with existing clients):
 *   id: <event id>
 *   event: goal
 *   data: {"matchId":"...", ...}
 *
 * In commentary format (?format=commentary):
 *   id: <event id>
 *   event: goal
 *   data: {"eventId":"...","matchId":"...","type":"GOAL","severity":"CRITICAL","minute":...,"team":"...","commentary":"...","timestamp":"..."}
 */
export function formatSseMessage(event: MatchEvent, options?: SseFormatOptions): string {
  if (options?.format === 'commentary') {
    const minute =
      'minute' in event.payload && typeof event.payload.minute === 'number'
        ? event.payload.minute
        : 0;
    const team =
      'team' in event.payload && typeof event.payload.team === 'string'
        ? event.payload.team
        : 'Unknown';

    let commentary = event.commentary ?? `${event.type.toUpperCase()} occurred in minute ${minute}`;

    if (options?.style === 'concise') {
      if (event.type === 'goal') {
        commentary = `${minute}' — GOAL ${team}. ${event.payload.player} (${event.payload.score}).`;
      } else if (event.type === 'card') {
        const cType = event.payload.cardType === 'red' ? 'RED CARD' : 'YELLOW CARD';
        commentary = `${minute}' — ${cType} ${event.payload.player} (${team}).`;
      } else if (event.type === 'substitution') {
        commentary = `${minute}' — SUB ${team}: ${event.payload.playerIn} on for ${event.payload.playerOut}.`;
      }
    } else if (options?.style === 'professional') {
      if (event.type === 'goal') {
        commentary = `${team} move ahead following a successful attacking sequence finished by ${event.payload.player} in minute ${minute} (${event.payload.score}).`;
      } else if (event.type === 'card') {
        const isRed = event.payload.cardType === 'red';
        commentary = isRed
          ? `${team} are reduced to 10 players as ${event.payload.player} receives a straight red card in minute ${minute}.`
          : `${event.payload.player} of ${team} is shown a yellow card by the referee for a disciplinary infraction in minute ${minute}.`;
      } else if (event.type === 'substitution') {
        commentary = `${team} execute a tactical alteration: ${event.payload.playerIn} enters the pitch in place of ${event.payload.playerOut} (minute ${minute}).`;
      }
    }

    const commentaryData = {
      eventId: event.id,
      matchId: event.matchId,
      type: event.type.toUpperCase(),
      severity: event.severity ?? (event.type === 'goal' ? 'CRITICAL' : event.type === 'card' ? 'HIGH' : 'LOW'),
      minute,
      team,
      commentary,
      timestamp: new Date(event.detectedAt).toISOString(),
    };
    return `id: ${event.id}\nevent: ${event.type}\ndata: ${JSON.stringify(commentaryData)}\n\n`;
  }

  const data = JSON.stringify(event.payload);
  return `id: ${event.id}\nevent: ${event.type}\ndata: ${data}\n\n`;
}

/** Serialize an SSE comment line (used for keep-alive frames). */
export function formatSseComment(comment: string): string {
  return `: ${comment}\n\n`;
}
